### ISSUE TITLE
关于net的疑惑

### ISSUE THREAD

**Issue by WZZ233** [mpskex/Convolutional-Pose-Machine-tf#10]
您好！感谢您的分享！
我对net文件夹里的文件的具体含义稍微有一些疑惑：
1. PPNnMask.py指代的是R-CNN吗？
2. MobileCPM的结构与原本的CPM的区别在哪里呢？
由于我是刚入门计算机视觉的新手，提出的问题可能比较粗浅，望谅解！
再次感谢您的分享！

**Comment by mpskex** [comment]
1. PPNnMask is an experimental code that is designed to resemble the MaskRCNN structure, and it is still under testing. There are no usable model for this currently.

2. mobileCPM uses separable convolutional layers(depthwise+1*1) to build up the multi-stage architecture. Also it uses mobileNet as a backbone. So it’s light and fast.

As this issue is no longer active, I will temporarily close this issue. You can re-open it at any time.
